Docs: sudo is required on the apt-key add not on wget (#18180)
Running the command as given in the current doc throws the error:

```
sudo wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -
ERROR: This command can only be used by root.
```

The proposed change fixes this issue.